import coreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

/**
 * ESLint flat config.
 *
 * eslint-config-next 16 exports flat configs directly, so there is no
 * FlatCompat shim here.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'src/types/database.ts', // generated by `npm run db:types`
      'playwright-report/**',
      'test-results/**',
      'supabase/functions/**', // Deno runtime — linted separately
    ],
  },

  ...coreWebVitals,
  ...nextTypescript,

  {
    rules: {
      // Rules that matter for this codebase specifically.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // console.log risks printing personal data; warn and error are kept for
      // genuine failures, which are redacted before they reach a log sink.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
];

export default config;
